### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by sergiokml** [zejji/DbContextScopeEFCore6#45]
How should I implement "beginTransaction" for an insert of 3 different tables (I have to make sure that all 3 are created), the second and the third need the first one to be inserted (PK).

**Comment by zejji** [comment]
Hi @sergiokml - I'm not 100% sure I've understood the context of your question, but the issue of saving multiple related entities is handled already by Entity Framework Core: see https://docs.microsoft.com/en-us/ef/core/saving/related-data#adding-a-graph-of-new-entities. In short, related entities can be added (without setting the primary key value) to a graph of objects and EF Core will handle saving the various entities to the database and tying the PK and FK values up as part of a single database transaction.

The main purpose of the DbContextScope is to allow different locations in the code to access the same ambient DbContext instance (which represents a unit of work) without passing the DbContext explicitly from location to location, so that Entity Framework can do its magic. It's also worth being aware of the information in [this article](https://docs.microsoft.com/en-us/ef/core/change-tracking/entity-entries) if, for some reason, you need to inspect the new and as-yet unsaved entities contained in the DbContext.

I definitely recommend reading Mehdi El Gueddari's original article at https://mehdi.me/ambient-dbcontext-in-ef6/ if you haven't seen it already, as it's a very thorough description of the problem which the DbContextScope solves.

Let me know if I've misunderstood your question! 🙂

**Comment by sergiokml** [comment]
Hi, thank you for you answer. These 3 tables are not related, so EF could not be used for the insert through their keys. Before using your project I only did a "beginTransaction" and the 3 tables were inserted correctly. Now with your project I need to be able to create first one, then the other 2 (because they need the ID). The restriction is that all 3 have to be created otherwise "rollback" would have to be applied. Maybe with your project you should nest each table? Is it possible to wrap all that in a transaction?

**Comment by zejji** [comment]
Since the main aim of the DbContextScope is to allow the business logic to manage the lifetime of an ambient DbContext (or multiple DbContexts), I don't think your use case is the primary one envisaged by the library. This is particularly the case given that SaveChanges() can only be called once on the DbContextScope unless there is a DbConcurrencyException.

However, given your requirements, perhaps one of the following workarounds would do the job?:

1. Create a relationship between the tables in EF Core **despite** the absence of foreign keys. [This thread](https://github.com/dotnet/efcore/issues/15854) gives some information on how to do this. The code would, however, need to handle errors thrown if, for some reason, a related entity did not exist.

2. Use IDbContextScopeFactory's CreateWithTransaction method (see [here](https://github.com/zejji/DbContextScopeEFCore6/blob/main/DbContextScope/Interfaces/IDbContextScopeFactory.cs#:~:text=CreateReadOnly(DbContextScopeOption%20joiningOption%20%3D%20DbContextScopeOption.JoinExisting)%3B-,///%20%3Csummary%3E,IDbContextScope%20CreateWithTransaction(IsolationLevel%20isolationLevel)%3B,-///%20%3Csummary%3E)). Note the comments about not keeping the transaction open for any longer than strictly necessary. Also, because of the limitation mentioned above about only being able to call SaveChanges() once on the DbContextScope, you would need to call SaveChanges() on the underlying DbContext instead (which you can fetch from the DbContextScope by calling dbContextScope.DbContexts.Get<TDbContext>()).
